.PHONY: install live run

install:
	npm install contentful

live:
	open 'https://assets.contentful.com/crvcnjrd7aj2/25yupHorJGkey6cuE82EEO/966df7fb945414b77493d81dcc6fe1d2/index.html'

run:
	@$(HOME)/Downloads/gatling-0.13/gatling
